### ISSUE TITLE
Add Plugin_Config again

### ISSUE THREAD

**Issue by TheUltimateC0der** [tghamm/dynamic-linq-query-builder#103]
I have searched for a way to configure plugins, but havent found a way to do so.

I stumled upon a commit a few years ago (https://github.com/tghamm/dynamic-linq-query-builder/commit/2285ed710fa4d44a8ef8f9efd9894a19d599003d), where Plugin_config has been removed.

I would love to see it added again, since people are currently unable to configure their plugins.

**Comment by tghamm** [comment]
Hi @TheUltimateC0der per the commit notes, it seems that the consensus was that the plugin object was just too messy/complicated, and that the builder included in this library is pretty simplistic.  Would it not make more sense to define your schema client-side as the commit suggests?  I could be convinced to bring it back, but this does seem like covered ground a little bit.  Let me know your thoughts!

**Comment by TheUltimateC0der** [comment]
I define everything in code, since I use this code at some other places to make my life easier. Having to define it in JS and my code forces me to take care of both things instead of just one.

**Comment by tghamm** [comment]
@TheUltimateC0der this will be added back in #112 apologies for the delay.
