### ISSUE TITLE
Dictionary<string, object> Support

### ISSUE THREAD

**Issue by Ilanlido** [tghamm/dynamic-linq-query-builder#104]
Hey @tghamm
I want to add support for dictionary<string,object> property and would like to know what you think about it / how available you are to push an update for it.
My plan is to add it to BuildNestedExpression where instead of getting the property of the type i will check if it's dictionary and if so create an expression to check if the field exists in the dictionary and create the expression with the rest of the logic.
Let me know what you think, Thanks!

**Comment by tghamm** [comment]
Thanks for the PR.  Merged #105 will release a new version here shortly.
