### ISSUE TITLE
Sign assembly to make it available to signed libraries

### ISSUE THREAD

**Issue by DaveSenn** [tghamm/dynamic-linq-query-builder#15]
@tghamm 

Thanks for your work on this library. Love to use it together with JQuery-QueryBuilder.
I’d like to use your library in one of my company’s projects. 
Sadly, our libraries have to be signed. Since dynamic-linq-query-builder is not signed we are not able to use it.
Would it be ok for you to sign your library? If so, I would be happy to help you with a pull request.

**Comment by tghamm** [comment]
@DaveSenn You're welcome, I'm glad you've found it helpful.  I see no reason we couldn't offer a signed version of the package.  I can look at this next week, or if you have a solution in mind already, I'd happily accept a pull-request. Just let me know what you are thinking.

**Comment by DaveSenn** [comment]
@tghamm  Thanks for the quick response.
I’ve created a pull-request which adds a new key file and signs the assembly with it.
https://github.com/castle-it/dynamic-linq-query-builder/pull/16 

The build is still working (on my machine). Some of the tests didn’t run correctly on my system, but I think it has nothing to do with my changes (Looks like the tests are failing because I’ve different culture settings).
[All tests from Solution.zip](https://github.com/castle-it/dynamic-linq-query-builder/files/1003700/All.tests.from.Solution.zip)

The build on the CI seems to have a problem with my changes. 
I failed to reproduce this problem on my system:
-	The NUnit tests did run correctly [TestResult.zip](https://github.com/castle-it/dynamic-linq-query-builder/files/1003723/TestResult.zip)
-	OpenCover did run correctly [opencoverCoverage.zip](https://github.com/castle-it/dynamic-linq-query-builder/files/1003726/opencoverCoverage.zip)
-	I could not tests coveralls because of the missing repo token
