### ISSUE TITLE
Problem with Date comparision

### ISSUE THREAD

**Issue by kewinbrand** [tghamm/dynamic-linq-query-builder#49]
Hi,

When a field is of date type the comparison is not made taking into account only the date, the time is also taken. The comparision should be:

queryable.Where(entity => entity.dateTimeProperty.Value == DateTime.Now.Date)

At the time it does:

queryable.Where(entity => entity.dateTimeProperty.Value == filterRule.Value (parse, etc etc) )

I dig up a little bit into the code and found that no distinction is made between Date and DateTime types:
class QueryBuilder, BuildExpressionTree method

```
Type type;

switch (rule.Type)
{
    case "integer":
        type = typeof(int);
        break;
    case "double":
        type = typeof(double);
        break;
    case "string":
        type = typeof(string);
        break;
    case "date":
    case "datetime":
        type = typeof(DateTime);
        break;
    case "boolean":
        type = typeof(bool);
        break;
    default:
        throw new Exception($"Unexpected data type {rule.Type}");
}
```
Is there any catch to it or is it a bug?

Cheers

**Comment by shapemetrics** [comment]
In C# all dates are datetime no matter what is in SQL. 

Though I do agree with you, there is a bug related to dates, I haven't been able to find out the problem.

**Comment by kewinbrand** [comment]
Hey,

Ok, what bug is that? Maybe I can help with it.
Indeed there is no distiction between date and datetime in C# but when you compare only the 'Date' property of your field the where statement is generated w/o the time part.

queryable.Where(entity => entity.dateTimeProperty.Date == filterRule.Value (parse, etc etc).Date )

**Comment by shapemetrics** [comment]
I found it, my foolish oversight was the bug.
