### ISSUE TITLE
How to implement class per hierarchy in dynamic query 

### ISSUE THREAD

**Issue by skirkole** [tghamm/dynamic-linq-query-builder#50]
Hi 

We need to include an entity dynamically which is a derived entity  using table-per-hierarchy.
e.g. 
class Customer 
{
..
public virtual List<CustomerXDetails> CustomerXDetail
}
where 
CustomerXDetails : CustomerDetails 
CustomerYDetails: CustomerDetails

When we do 
 .Include (c=> c.CustomerXDetails) , we are getting  NullReferenceException.

I want to append dynamic filter on CustomerXDetails. 

Quick help is appreciated !!

Thanks .

**Comment by MohammmedSalah** [comment]
you can see this one  #13
