### ISSUE TITLE
Is it possible to filter over another field value?

### ISSUE THREAD

**Issue by MasallahOZEN** [tghamm/dynamic-linq-query-builder#57]
Hi, is it possible to filter over another field value?

Thnx
Best Regards

**Comment by liacolo87** [comment]
Have you found an answer? I am interested in knowing the same

**Comment by liacolo87** [comment]
this works

"queryBuilderFilterRule": {
        "condition": "or",
        "rules": [
            {
                "condition": "and",
                "field": "Name",
                "id": "Name",
                "input": "NA",
                "operator": "equal",
                "type": "string",
                "value": [
                    "some"
                ]
            },
            {
                "field": "Date",
                "id": "Date",
                "input": "NA",
                "operator": "between",
                "type": "datetime",
                "value": [
                    "01/07/2021",
                    "30/08/2021"
                ]
            }
        ]
    }
