### ISSUE TITLE
Is it possible to get triggered rule for each result 

### ISSUE THREAD

**Issue by Jillustre96** [tghamm/dynamic-linq-query-builder#75]
Hi, We use this query builder with jquerybuilder and it work like a charm. But now, we want to know which XYZ rule give me "True" result for a specific set of data.

Ex: rule-> goal >10 or (goal > 5 and assist > 5)

record 1 (answer to rule)
record 2 (dosen't answer to rule)
record 3(answer to rule)

so for record 1 and 3 which makes them come out as what they meet the rules

Is it possible?

thanks!

**Comment by tghamm** [comment]
I don't think it's possible. This builds an expression tree along the way, I'm not sure how you would add callbacks to understand where the logic actually lies.
