### ISSUE TITLE
Type field in QueryBuilderFilterRule

### ISSUE THREAD

**Issue by markikordahi** [tghamm/dynamic-linq-query-builder#88]
Hi!
I'm simply wondering why are you using the field type from frontend instead of checking the property type on the backend ?
Not sure if I'm missing anything.. 
I guess we can maybe allow the user the pass a type to override (not sure if its ever needed) ?

Quick example:
In your sample project you have class PersonRecord with Age an object of data type int
```
public class PersonRecord
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public DateTime Birthday { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public ICollection<Book> Books { get; set; }
        public ICollection<Course> Courses { get; set; }
    }
```

when passing a filter to Age, why do i have to specify the type from the frontend ? wouldnt it make more sense to get the type from its class ?

**Comment by tghamm** [comment]
This is a byproduct of the project's initial compatibility with `jQuery-QueryBuilder`, which has that specification, though you could implement your own `IFilterRule` that parses this out on the back-end if you wanted to.
