### ISSUE TITLE
Error when using Between operator and type double

### ISSUE THREAD

**Issue by liacolo** [tghamm/dynamic-linq-query-builder#97]
The following rule produces a parsing error:

Condition = And
Field = Amount
Type = Double
Operator = Between
Value = [ "0", "0.99" ]

But other operators like Greater work fine with Value = [ "0.99" ]

Stack trace:

System.ArgumentException: 0.99 is not a valid value for Double. (Parameter 'value')
---> System.FormatException: Input string was not in a correct format.   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)   at System.Double.Parse(String s, NumberStyles style, IFormatProvider provider)   at System.ComponentModel.DoubleConverter.FromString(String value, NumberFormatInfo formatInfo)   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)   --- End of inner exception stack trace ---   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.GetConstants(Type type, Object value, Boolean isCollection, BuildExpressionOptions options)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.Between(Type type, Object value, Expression propertyExp, BuildExpressionOptions options)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildOperatorExpression(Expression propertyExp, IFilterRule rule, BuildExpressionOptions options, Type type)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildExpressionTree(ParameterExpression pe, IFilterRule rule, BuildExpressionOptions options)   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildExpressionTree(ParameterExpression pe, IFilterRule rule, BuildExpressionOptions options)   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildExpressionTree(ParameterExpression pe, IFilterRule rule, BuildExpressionOptions options)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildExpressionLambda[T](IFilterRule filterRule, BuildExpressionOptions options, String& parsedQuery)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildQuery[T](IQueryable`1 queryable, IFilterRule filterRule, BuildExpressionOptions options, String& parsedQuery)   at Castle.DynamicLinqQueryBuilder.QueryBuilder.BuildQuery[T](IQueryable`1 queryable, IFilterRule filterRule, BuildExpressionOptions options)

**Comment by tghamm** [comment]
@liacolo Can you provide more information about the `CultureInfo`, and any other calling params?  This case has a unit test for it that is passing, so I'm not sure what to test without more information.  Thanks!

**Comment by liacolo** [comment]
Hi, thanks for your response

I tried to pass CultureInfo.InvariantCulture as a parameter to BuildQuery, but it seems to be using the server's default (which in my case is "es-ES", so the parsing of "0.99" fails because in this culture the decimal separator is the comma).

Looking at the QueryBuilder code, the problem seems to be in this line, which should consider using the CultureInfo contained in the options:
https://github.com/tghamm/dynamic-linq-query-builder/blob/d177fff0632dd754eeb83f5d2ef55c7cc4e5d926/Castle.DynamicLinqQueryBuilder/QueryBuilder.cs#L498

**Comment by tghamm** [comment]
@liacolo you are right, in this case (and a few others), it's not respecting the CultureInfo.  It will probably be a week or so before I can take a look at fixing this, but I should be able to fix this, or a PR is welcome.  Thanks for bringing this up!

**Comment by tghamm** [comment]
@liacolo my latest commit and release should address this, thanks again for raising the issue.

**Comment by liacolo** [comment]
This solved our problem, thanks a lot
